/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--background) / <alpha-value>)",
        foreground: "rgb(var(--foreground) / <alpha-value>)",
        surface: {
          DEFAULT: "rgb(var(--surface) / <alpha-value>)",
          muted: "rgb(var(--surface-muted) / <alpha-value>)",
          raised: "rgb(var(--surface-raised) / <alpha-value>)",
        },
        muted: {
          foreground: "rgb(var(--muted-foreground) / <alpha-value>)",
        },
        subtle: "rgb(var(--subtle) / <alpha-value>)",
        border: {
          DEFAULT: "rgb(var(--border) / <alpha-value>)",
          strong: "rgb(var(--border-strong) / <alpha-value>)",
        },
        input: "rgb(var(--input) / <alpha-value>)",
        ring: "rgb(var(--ring) / <alpha-value>)",
        brand: {
          DEFAULT: "rgb(var(--brand) / <alpha-value>)",
          foreground: "rgb(var(--brand-foreground) / <alpha-value>)",
          hover: "rgb(var(--brand-hover) / <alpha-value>)",
          active: "rgb(var(--brand-active) / <alpha-value>)",
          subtle: "rgb(var(--brand-subtle) / <alpha-value>)",
          "subtle-foreground": "rgb(var(--brand-subtle-foreground) / <alpha-value>)",
          "subtle-border": "rgb(var(--brand-subtle-border) / <alpha-value>)",
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
        accent: {
          DEFAULT: "rgb(var(--accent) / <alpha-value>)",
          foreground: "rgb(var(--accent-foreground) / <alpha-value>)",
          hover: "rgb(var(--accent-hover) / <alpha-value>)",
          subtle: "rgb(var(--accent-subtle) / <alpha-value>)",
          "subtle-foreground": "rgb(var(--accent-subtle-foreground) / <alpha-value>)",
          "subtle-border": "rgb(var(--accent-subtle-border) / <alpha-value>)",
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          300: "#5eead4",
          400: "#2dd4bf",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          800: "#115e59",
          900: "#134e4a",
          950: "#042f2e",
        },
        success: {
          DEFAULT: "rgb(var(--success) / <alpha-value>)",
          subtle: "rgb(var(--success-subtle) / <alpha-value>)",
          "subtle-foreground": "rgb(var(--success-subtle-foreground) / <alpha-value>)",
          "subtle-border": "rgb(var(--success-subtle-border) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "rgb(var(--warning) / <alpha-value>)",
          subtle: "rgb(var(--warning-subtle) / <alpha-value>)",
          "subtle-foreground": "rgb(var(--warning-subtle-foreground) / <alpha-value>)",
          "subtle-border": "rgb(var(--warning-subtle-border) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "rgb(var(--destructive) / <alpha-value>)",
          foreground: "rgb(var(--destructive-foreground) / <alpha-value>)",
          hover: "rgb(var(--destructive-hover) / <alpha-value>)",
          subtle: "rgb(var(--destructive-subtle) / <alpha-value>)",
          "subtle-foreground": "rgb(var(--destructive-subtle-foreground) / <alpha-value>)",
          "subtle-border": "rgb(var(--destructive-subtle-border) / <alpha-value>)",
        },
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
      },
      boxShadow: {
        glow: "0 10px 30px -10px rgb(var(--brand) / 0.35)",
        "glow-accent": "0 10px 30px -10px rgb(var(--accent) / 0.35)",
        panel:
          "0 1px 3px 0 rgb(var(--shadow-color) / 0.06), 0 1px 2px -1px rgb(var(--shadow-color) / 0.06)",
        card:
          "0 4px 16px -4px rgb(var(--shadow-color) / 0.08), 0 2px 6px -2px rgb(var(--shadow-color) / 0.06)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-400px 0" },
          "100%": { backgroundPosition: "400px 0" },
        },
      },
      animation: {
        "fade-in": "fadeIn 0.35s ease-out",
        shimmer: "shimmer 1.2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
